baseURL = 'https://www.bitsflippin.xyz/'
languageCode = 'en-us'
title = 'Bitsflippin Tech Services - macOS Repair/Software support and Cloud & Tech Workshops'
theme = 'ananke'

enableGitInfo = true

[frontmatter]
lastmod = [':git', ':fileModTime']

# Load static images from a dedicated folder. 
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'
